version: "3.8"

services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    working_dir: /app
    stdin_open: true
    tty: true

  api:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=django-insecure-!t(63131+el@f=60i5tvyo#_fxovs9+i6*rh4(lytdj!i_nefg
    working_dir: /app
    tty: true

networks:
  default:
    name: app-network
