version: "3.8"

services:
  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    stdin_open: true
    tty: true

  api:
    build: ./Backend
    volumes:
      - ./Backend:/app
    ports:
      - 8000:8000
    working_dir: /app
    tty: true

networks:
  default:
    name: app-network
