version: "3.8"

services:
  django:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=django-insecure-!t(63131+el@f=60i5tvyo#_fxovs9+i6*rh4(lytdj!i_nefg
    working_dir: /app
    tty: true

networks:
  default:
    name: app-network
